# Generated by Django 4.0.5 on 2022-06-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='neighborhood',
            new_name='hood',
        ),
    ]
