# Generated by Django 4.0.5 on 2022-06-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_neighborhood_post_hood'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='hoodphoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
