# Generated by Django 4.0.5 on 2022-06-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_neighborhood_description_neighborhood_hoodphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='occupants',
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='app.neighborhood'),
        ),
    ]
